package s3iam

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// realPolicyDir is the policy set actually attached to LDAP groups in
// MinIO/AIStor (generated by policy/gen_policies.py). Testing against it
// rather than a private copy means this test fails loudly if the two ever
// drift apart — which is the whole risk of a mirror design.
const realPolicyDir = "../../policy/generated"

// realAttachments is the declaration generated alongside those policies.
const realAttachments = "../../policy/attachments.yaml"

func loadRealAttachments(t *testing.T) *Attachments {
	t.Helper()
	a, err := LoadAttachments(realAttachments)
	if err != nil {
		t.Fatalf("LoadAttachments(%q): %v", realAttachments, err)
	}
	return a
}

// grants resolves the sources for a user in the given group CNs, using the
// deployment's real group base DN.
func grants(t *testing.T, groupCNs ...string) []Source {
	t.Helper()
	dns := make([]string, len(groupCNs))
	for i, cn := range groupCNs {
		dns[i] = "cn=" + cn + ",ou=groups,dc=example,dc=com"
	}
	return loadRealAttachments(t).Resolve("", dns)
}

func loadRealCatalog(t *testing.T) *Catalog {
	t.Helper()
	catalog, err := LoadCatalog(realPolicyDir)
	if err != nil {
		t.Fatalf("LoadCatalog(%q): %v", realPolicyDir, err)
	}
	return catalog
}

func TestLoadCatalogReadsRealPolicySet(t *testing.T) {
	catalog := loadRealCatalog(t)
	want := []string{
		"bi-adm", "bi-dev", "bi-view",
		"ml-adm", "ml-dev", "ml-view",
		"ops-adm", "ops-dev", "ops-view",
	}
	got := catalog.Names()
	if len(got) != len(want) {
		t.Fatalf("Names() = %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("Names() = %v, want %v", got, want)
		}
	}
	if catalog.Digest == "" {
		t.Error("Digest should fingerprint the loaded policy set")
	}
	if catalog.LoadedAt.IsZero() {
		t.Error("LoadedAt should be set")
	}
}

func TestLoadCatalogDigestIsStableAndContentSensitive(t *testing.T) {
	first := loadRealCatalog(t)
	second := loadRealCatalog(t)
	if first.Digest != second.Digest {
		t.Errorf("digest should be stable across loads: %q vs %q", first.Digest, second.Digest)
	}

	dir := t.TempDir()
	path := filepath.Join(dir, "bi-view.json")
	if err := os.WriteFile(path, []byte(`{"Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::team-bi/*"}]}`), 0o600); err != nil {
		t.Fatal(err)
	}
	before, err := LoadCatalog(dir)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(`{"Statement":[{"Effect":"Allow","Action":"s3:DeleteObject","Resource":"arn:aws:s3:::team-bi/*"}]}`), 0o600); err != nil {
		t.Fatal(err)
	}
	after, err := LoadCatalog(dir)
	if err != nil {
		t.Fatal(err)
	}
	if before.Digest == after.Digest {
		t.Error("digest should change when a policy's contents change")
	}
}

func TestLoadCatalogEmptyDirIsError(t *testing.T) {
	// A bad mount path must fail loudly: silently showing every user
	// "권한 없음" is the worst failure mode for this feature.
	if _, err := LoadCatalog(t.TempDir()); err == nil {
		t.Error("expected an error for a directory with no policy documents")
	}
}

func TestLoadCatalogRejectsMalformedPolicy(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "broken.json"), []byte("{not json"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := LoadCatalog(dir); err == nil {
		t.Error("expected an error for a malformed policy document")
	}
}

// capsOf returns the capabilities the access grants for one bucket.
func capsOf(a Access, bucket string) []Capability {
	for _, b := range a.Buckets {
		if b.Bucket == bucket {
			return b.Capabilities
		}
	}
	return nil
}

func sameCaps(got, want []Capability) bool {
	if len(got) != len(want) {
		return false
	}
	for i := range got {
		if got[i] != want[i] {
			return false
		}
	}
	return true
}

func TestResolveTierCapabilities(t *testing.T) {
	catalog := loadRealCatalog(t)
	tests := []struct {
		group string
		want  []Capability
	}{
		{"bi-view", []Capability{CapList, CapRead}},
		// dev reads lifecycle rules but cannot set them: PutLifecycleConfiguration
		// is an indirect delete path (an "Expiration: Days 1" ILM rule), so it
		// sits in the adm tier alongside DeleteObject.
		{"bi-dev", []Capability{CapList, CapRead, CapLifecycleRead, CapWrite}},
		{"bi-adm", []Capability{CapList, CapRead, CapLifecycleRead, CapWrite, CapLifecycleWrite, CapDelete, CapBucketPolicy}},
	}
	for _, tt := range tests {
		access := catalog.Resolve(grants(t, tt.group))
		if len(access.Warnings) != 0 {
			t.Errorf("%s: unexpected warnings %v", tt.group, access.Warnings)
		}
		if got := capsOf(access, "team-bi"); !sameCaps(got, tt.want) {
			t.Errorf("%s: team-bi = %v, want %v", tt.group, got, tt.want)
		}
	}
}

func TestResolveAdmGrantsAccountWideServiceAccount(t *testing.T) {
	access := loadRealCatalog(t).Resolve(grants(t, "ops-adm"))
	if got := capsOf(access, "*"); !sameCaps(got, []Capability{CapServiceAccount}) {
		t.Errorf(`bucket "*" = %v, want [serviceAccount]`, got)
	}
	// The account-wide pseudo-bucket sorts last so it never leads the table.
	if last := access.Buckets[len(access.Buckets)-1].Bucket; last != "*" {
		t.Errorf(`last bucket = %q, want "*"`, last)
	}
	if names := access.BucketNames(); len(names) != 1 || names[0] != "team-ops" {
		t.Errorf("BucketNames() = %v, want [team-ops]", names)
	}
}

func TestResolveUnionsMultipleTeams(t *testing.T) {
	// The multi-team case the dashboard was built for: dev on one team,
	// read-only on another. A plain union is correct only because the
	// policy set is Allow-only.
	access := loadRealCatalog(t).Resolve(grants(t, "ml-view", "bi-dev"))
	if got := capsOf(access, "team-bi"); !sameCaps(got, []Capability{CapList, CapRead, CapLifecycleRead, CapWrite}) {
		t.Errorf("team-bi = %v", got)
	}
	if got := capsOf(access, "team-ml"); !sameCaps(got, []Capability{CapList, CapRead}) {
		t.Errorf("team-ml = %v", got)
	}
	if !access.Can("team-bi", CapWrite) || access.Can("team-ml", CapWrite) {
		t.Error("write should be granted on team-bi only")
	}
	// Neither the direct nor the indirect (ILM expiration) delete path may
	// appear in a dev/view tier.
	for _, bucket := range []string{"team-bi", "team-ml"} {
		for _, c := range []Capability{CapDelete, CapLifecycleWrite} {
			if access.Can(bucket, c) {
				t.Errorf("%s should not grant %s below the adm tier", bucket, c)
			}
		}
	}
	// Buckets are sorted, independent of the order LDAP returned groups in.
	if names := access.BucketNames(); len(names) != 2 || names[0] != "team-bi" || names[1] != "team-ml" {
		t.Errorf("BucketNames() = %v, want [team-bi team-ml]", names)
	}
}

func TestResolveAttributesEachGrantToItsGroup(t *testing.T) {
	access := loadRealCatalog(t).Resolve(grants(t, "bi-dev", "ml-view"))
	for _, b := range access.Buckets {
		if len(b.Via) != 1 {
			t.Fatalf("%s: Via = %v, want exactly one source", b.Bucket, b.Via)
		}
		want := map[string]string{"team-bi": "bi-dev", "team-ml": "ml-view"}[b.Bucket]
		wantDN := "cn=" + want + ",ou=groups,dc=example,dc=com"
		if b.Via[0].Kind != SubjectGroup || b.Via[0].DN != wantDN || b.Via[0].Policy != want {
			t.Errorf("%s: Via = %+v, want group %q policy %q", b.Bucket, b.Via[0], wantDN, want)
		}
	}
}

func TestResolveIgnoresGroupsWithNoPolicy(t *testing.T) {
	// Bare role groups and org-wide groups are not S3 policies; warning
	// about each would bury the warnings that matter.
	access := loadRealCatalog(t).Resolve(grants(t, "adm", "everyone", "bi-view"))
	if len(access.Warnings) != 0 {
		t.Errorf("unmapped groups should be silent, got %v", access.Warnings)
	}
	if names := access.BucketNames(); len(names) != 1 || names[0] != "team-bi" {
		t.Errorf("BucketNames() = %v, want [team-bi]", names)
	}
}

func TestResolveNoGroupsGrantsNothing(t *testing.T) {
	access := loadRealCatalog(t).Resolve(nil)
	if len(access.Buckets) != 0 {
		t.Errorf("expected no access, got %v", access.Buckets)
	}
	// Non-nil so the API serialises this as [], not null.
	if access.Buckets == nil {
		t.Error("Buckets should be an empty slice, not nil")
	}
}

// The declaration, not a name convention, decides what a group holds — so a
// group whose CN looks nothing like its policy resolves correctly, and a
// group can hold more than one policy. Neither was expressible before.
func TestAttachmentsDeclarationBeatsNamingConvention(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "a.yaml")
	if err := os.WriteFile(path, []byte(`
attachments:
  - policy: bi-view
    groups: ["cn=analytics-readers,ou=groups,dc=example,dc=com"]
  - policy: ml-view
    groups: ["cn=analytics-readers,ou=groups,dc=example,dc=com"]
`), 0o600); err != nil {
		t.Fatal(err)
	}
	attachments, err := LoadAttachments(path)
	if err != nil {
		t.Fatal(err)
	}
	sources := attachments.Resolve("", []string{"cn=analytics-readers,ou=groups,dc=example,dc=com"})
	if len(sources) != 2 {
		t.Fatalf("one group holding two policies should yield two sources, got %+v", sources)
	}
	access := loadRealCatalog(t).Resolve(sources)
	if !access.Can("team-bi", CapRead) || !access.Can("team-ml", CapRead) {
		t.Errorf("both attached policies should contribute, got %+v", access.Buckets)
	}
}

// MinIO also attaches policies straight to a user DN. The naming-convention
// lookup could not see those at all.
func TestAttachmentsResolveUserDN(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "a.yaml")
	if err := os.WriteFile(path, []byte(`
attachments:
  - policy: ops-adm
    users: ["uid=oncall,ou=users,dc=example,dc=com"]
`), 0o600); err != nil {
		t.Fatal(err)
	}
	attachments, err := LoadAttachments(path)
	if err != nil {
		t.Fatal(err)
	}
	sources := attachments.Resolve("uid=oncall,ou=users,dc=example,dc=com", nil)
	if len(sources) != 1 || sources[0].Kind != SubjectUser {
		t.Fatalf("expected one user-kind source, got %+v", sources)
	}
	if !loadRealCatalog(t).Resolve(sources).Can("team-ops", CapDelete) {
		t.Error("a policy attached to the user DN should grant its capabilities")
	}
}

// DNs are compared case-insensitively with optional spaces after commas —
// directories and MinIO disagree on both, and a DN that fails to match looks
// exactly like "no permissions".
func TestAttachmentsNormaliseDN(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "a.yaml")
	if err := os.WriteFile(path, []byte(`
attachments:
  - policy: bi-view
    groups: ["CN=Bi-View, OU=Groups, DC=Example, DC=Com"]
`), 0o600); err != nil {
		t.Fatal(err)
	}
	attachments, err := LoadAttachments(path)
	if err != nil {
		t.Fatal(err)
	}
	sources := attachments.Resolve("", []string{"cn=bi-view,ou=groups,dc=example,dc=com"})
	if len(sources) != 1 {
		t.Fatalf("DN spelling differences must still match, got %+v", sources)
	}
}

func TestLoadAttachmentsEmptyIsError(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "a.yaml")
	if err := os.WriteFile(path, []byte("attachments: []\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	// Same reasoning as an empty policy directory: a wrong path must not
	// render as "you have access to nothing".
	if _, err := LoadAttachments(path); err == nil {
		t.Error("expected an error for a declaration with no attachments")
	}
}

// A declared policy with no document is a split configuration, not a group
// that simply isn't ours — so it is reported rather than skipped.
func TestResolveWarnsOnAttachedPolicyWithNoDocument(t *testing.T) {
	access := loadRealCatalog(t).Resolve([]Source{
		{Kind: SubjectGroup, DN: "cn=ghost,ou=groups,dc=example,dc=com", Policy: "no-such-policy"},
	})
	if len(access.Warnings) != 1 {
		t.Fatalf("expected one warning, got %v", access.Warnings)
	}
	if !strings.Contains(access.Warnings[0], "no-such-policy") {
		t.Errorf("warning should name the missing policy, got %q", access.Warnings[0])
	}
}

// The generated declaration and the generated policy documents must not
// drift: every policy named in one has a document in the other.
func TestRealAttachmentsMatchRealPolicies(t *testing.T) {
	catalog := loadRealCatalog(t)
	for _, name := range loadRealAttachments(t).PolicyNames() {
		if _, err := LoadCatalog(realPolicyDir); err != nil {
			t.Fatal(err)
		}
		found := false
		for _, have := range catalog.Names() {
			if have == name {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("attachments reference policy %q with no document in %s", name, realPolicyDir)
		}
	}
}
