package s3iam

import (
	"os"
	"path/filepath"
	"testing"
)

// realPolicyDir is the policy set actually attached to LDAP groups in
// MinIO/AIStor (generated by policy/gen_policies.py). Testing against it
// rather than a private copy means this test fails loudly if the two ever
// drift apart — which is the whole risk of a mirror design.
const realPolicyDir = "../../policy/generated"

func loadRealCatalog(t *testing.T) *Catalog {
	t.Helper()
	catalog, err := LoadCatalog(realPolicyDir)
	if err != nil {
		t.Fatalf("LoadCatalog(%q): %v", realPolicyDir, err)
	}
	return catalog
}

func TestLoadCatalogReadsRealPolicySet(t *testing.T) {
	catalog := loadRealCatalog(t)
	want := []string{
		"bi-adm", "bi-dev", "bi-view",
		"ml-adm", "ml-dev", "ml-view",
		"ops-adm", "ops-dev", "ops-view",
	}
	got := catalog.Names()
	if len(got) != len(want) {
		t.Fatalf("Names() = %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("Names() = %v, want %v", got, want)
		}
	}
	if catalog.Digest == "" {
		t.Error("Digest should fingerprint the loaded policy set")
	}
	if catalog.LoadedAt.IsZero() {
		t.Error("LoadedAt should be set")
	}
}

func TestLoadCatalogDigestIsStableAndContentSensitive(t *testing.T) {
	first := loadRealCatalog(t)
	second := loadRealCatalog(t)
	if first.Digest != second.Digest {
		t.Errorf("digest should be stable across loads: %q vs %q", first.Digest, second.Digest)
	}

	dir := t.TempDir()
	path := filepath.Join(dir, "bi-view.json")
	if err := os.WriteFile(path, []byte(`{"Statement":[{"Effect":"Allow","Action":"s3:GetObject","Resource":"arn:aws:s3:::team-bi/*"}]}`), 0o600); err != nil {
		t.Fatal(err)
	}
	before, err := LoadCatalog(dir)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(`{"Statement":[{"Effect":"Allow","Action":"s3:DeleteObject","Resource":"arn:aws:s3:::team-bi/*"}]}`), 0o600); err != nil {
		t.Fatal(err)
	}
	after, err := LoadCatalog(dir)
	if err != nil {
		t.Fatal(err)
	}
	if before.Digest == after.Digest {
		t.Error("digest should change when a policy's contents change")
	}
}

func TestLoadCatalogEmptyDirIsError(t *testing.T) {
	// A bad mount path must fail loudly: silently showing every user
	// "권한 없음" is the worst failure mode for this feature.
	if _, err := LoadCatalog(t.TempDir()); err == nil {
		t.Error("expected an error for a directory with no policy documents")
	}
}

func TestLoadCatalogRejectsMalformedPolicy(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "broken.json"), []byte("{not json"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := LoadCatalog(dir); err == nil {
		t.Error("expected an error for a malformed policy document")
	}
}

// capsOf returns the capabilities the access grants for one bucket.
func capsOf(a Access, bucket string) []Capability {
	for _, b := range a.Buckets {
		if b.Bucket == bucket {
			return b.Capabilities
		}
	}
	return nil
}

func sameCaps(got, want []Capability) bool {
	if len(got) != len(want) {
		return false
	}
	for i := range got {
		if got[i] != want[i] {
			return false
		}
	}
	return true
}

func TestResolveTierCapabilities(t *testing.T) {
	catalog := loadRealCatalog(t)
	tests := []struct {
		group string
		want  []Capability
	}{
		{"bi-view", []Capability{CapList, CapRead}},
		// dev reads lifecycle rules but cannot set them: PutLifecycleConfiguration
		// is an indirect delete path (an "Expiration: Days 1" ILM rule), so it
		// sits in the adm tier alongside DeleteObject.
		{"bi-dev", []Capability{CapList, CapRead, CapLifecycleRead, CapWrite}},
		{"bi-adm", []Capability{CapList, CapRead, CapLifecycleRead, CapWrite, CapLifecycleWrite, CapDelete, CapBucketPolicy}},
	}
	for _, tt := range tests {
		access := catalog.Resolve([]string{tt.group}, nil)
		if len(access.Warnings) != 0 {
			t.Errorf("%s: unexpected warnings %v", tt.group, access.Warnings)
		}
		if got := capsOf(access, "team-bi"); !sameCaps(got, tt.want) {
			t.Errorf("%s: team-bi = %v, want %v", tt.group, got, tt.want)
		}
	}
}

func TestResolveAdmGrantsAccountWideServiceAccount(t *testing.T) {
	access := loadRealCatalog(t).Resolve([]string{"ops-adm"}, nil)
	if got := capsOf(access, "*"); !sameCaps(got, []Capability{CapServiceAccount}) {
		t.Errorf(`bucket "*" = %v, want [serviceAccount]`, got)
	}
	// The account-wide pseudo-bucket sorts last so it never leads the table.
	if last := access.Buckets[len(access.Buckets)-1].Bucket; last != "*" {
		t.Errorf(`last bucket = %q, want "*"`, last)
	}
	if names := access.BucketNames(); len(names) != 1 || names[0] != "team-ops" {
		t.Errorf("BucketNames() = %v, want [team-ops]", names)
	}
}

func TestResolveUnionsMultipleTeams(t *testing.T) {
	// The multi-team case the dashboard was built for: dev on one team,
	// read-only on another. A plain union is correct only because the
	// policy set is Allow-only.
	access := loadRealCatalog(t).Resolve([]string{"ml-view", "bi-dev"}, nil)
	if got := capsOf(access, "team-bi"); !sameCaps(got, []Capability{CapList, CapRead, CapLifecycleRead, CapWrite}) {
		t.Errorf("team-bi = %v", got)
	}
	if got := capsOf(access, "team-ml"); !sameCaps(got, []Capability{CapList, CapRead}) {
		t.Errorf("team-ml = %v", got)
	}
	if !access.Can("team-bi", CapWrite) || access.Can("team-ml", CapWrite) {
		t.Error("write should be granted on team-bi only")
	}
	// Neither the direct nor the indirect (ILM expiration) delete path may
	// appear in a dev/view tier.
	for _, bucket := range []string{"team-bi", "team-ml"} {
		for _, c := range []Capability{CapDelete, CapLifecycleWrite} {
			if access.Can(bucket, c) {
				t.Errorf("%s should not grant %s below the adm tier", bucket, c)
			}
		}
	}
	// Buckets are sorted, independent of the order LDAP returned groups in.
	if names := access.BucketNames(); len(names) != 2 || names[0] != "team-bi" || names[1] != "team-ml" {
		t.Errorf("BucketNames() = %v, want [team-bi team-ml]", names)
	}
}

func TestResolveAttributesEachGrantToItsGroup(t *testing.T) {
	access := loadRealCatalog(t).Resolve([]string{"bi-dev", "ml-view"}, nil)
	for _, b := range access.Buckets {
		if len(b.Via) != 1 {
			t.Fatalf("%s: Via = %v, want exactly one source", b.Bucket, b.Via)
		}
		want := map[string]string{"team-bi": "bi-dev", "team-ml": "ml-view"}[b.Bucket]
		if b.Via[0].GroupCN != want || b.Via[0].Policy != want {
			t.Errorf("%s: Via = %v, want group/policy %q", b.Bucket, b.Via[0], want)
		}
	}
}

func TestResolveIgnoresGroupsWithNoPolicy(t *testing.T) {
	// Bare role groups and org-wide groups are not S3 policies; warning
	// about each would bury the warnings that matter.
	access := loadRealCatalog(t).Resolve([]string{"adm", "everyone", "bi-view"}, nil)
	if len(access.Warnings) != 0 {
		t.Errorf("unmapped groups should be silent, got %v", access.Warnings)
	}
	if names := access.BucketNames(); len(names) != 1 || names[0] != "team-bi" {
		t.Errorf("BucketNames() = %v, want [team-bi]", names)
	}
}

func TestResolveNoGroupsGrantsNothing(t *testing.T) {
	access := loadRealCatalog(t).Resolve(nil, nil)
	if len(access.Buckets) != 0 {
		t.Errorf("expected no access, got %v", access.Buckets)
	}
	// Non-nil so the API serialises this as [], not null.
	if access.Buckets == nil {
		t.Error("Buckets should be an empty slice, not nil")
	}
}

func TestResolvePolicyMapOverridesNamingConvention(t *testing.T) {
	catalog := loadRealCatalog(t)
	access := catalog.Resolve([]string{"cn=analytics-team"}, map[string]string{"cn=analytics-team": "bi-view"})
	if got := capsOf(access, "team-bi"); !sameCaps(got, []Capability{CapList, CapRead}) {
		t.Errorf("team-bi = %v, want [list read]", got)
	}
	if via := access.Buckets[0].Via[0]; via.GroupCN != "cn=analytics-team" || via.Policy != "bi-view" {
		t.Errorf("Via = %v, want the group CN attributed to the mapped policy", via)
	}
}
